---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: ecommerce
  labels:
    app: auth-service
    component: authentication
spec:
  type: ClusterIP
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
    name: http
  selector:
    app: auth-service
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: ecommerce
  labels:
    app: user-service
    component: user-management
spec:
  type: ClusterIP
  ports:
  - port: 3002
    targetPort: 3002
    protocol: TCP
    name: http
  selector:
    app: user-service
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: ecommerce
  labels:
    app: product-service
    component: product-catalog
spec:
  type: ClusterIP
  ports:
  - port: 3003
    targetPort: 3003
    protocol: TCP
    name: http
  selector:
    app: product-service
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: ecommerce
  labels:
    app: order-service
    component: order-management
spec:
  type: ClusterIP
  ports:
  - port: 3004
    targetPort: 3004
    protocol: TCP
    name: http
  selector:
    app: order-service
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: ecommerce
  labels:
    app: payment-service
    component: payment-processing
spec:
  type: ClusterIP
  ports:
  - port: 3005
    targetPort: 3005
    protocol: TCP
    name: http
  selector:
    app: payment-service
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: ecommerce
  labels:
    app: notification-service
    component: notifications
spec:
  type: ClusterIP
  ports:
  - port: 3006
    targetPort: 3006
    protocol: TCP
    name: http
  selector:
    app: notification-service
---
apiVersion: v1
kind: Service
metadata:
  name: review-service
  namespace: ecommerce
  labels:
    app: review-service
    component: reviews
spec:
  type: ClusterIP
  ports:
  - port: 3007
    targetPort: 3007
    protocol: TCP
    name: http
  selector:
    app: review-service
---
apiVersion: v1
kind: Service
metadata:
  name: search-service
  namespace: ecommerce
  labels:
    app: search-service
    component: search-engine
spec:
  type: ClusterIP
  ports:
  - port: 3008
    targetPort: 3008
    protocol: TCP
    name: http
  selector:
    app: search-service
---
apiVersion: v1
kind: Service
metadata:
  name: shipping-service
  namespace: ecommerce
  labels:
    app: shipping-service
    component: shipping
spec:
  type: ClusterIP
  ports:
  - port: 3009
    targetPort: 3009
    protocol: TCP
    name: http
  selector:
    app: shipping-service 